logging:
  level:
    root: info

server:
    address: localhost
    port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/livedrawing?serverTimezone=Asia/Seoul
    username: root
    password: 1617
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
