logging:
  level:
    root: info

server:
    address: localhost
    port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/livedrawing
    username: root
    password: qpwoeialskdj1!H
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 234586769421-7gqq45aokbu6mn00rbg6gdcbekmd5ert.apps.googleusercontent.com
            client-secret: TOOZvTphSQVJOMZufd-sVErt
            scope:
              - email
              - profile

          facebook:
            client-id: 478476743196974
            client-secret: bdf89372f2b216f8a9229d298ca09135
            scope:
              - email
              - public_profile

          naver:
            client-id: GeNXm2d44PqqC3Dwf_7M
            client-secret: TjSPmF_L5w
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌.

